services:
  salmon_run_notifier:
    image: naruzosa/salmon_run_notifier:latest
    build:  # Fallback in case the image is unavailable
      context: .
      dockerfile: Dockerfile
    volumes:
      - C:\Your\Path\config:/app/config
    environment:
      - PYTHONUNBUFFERED=1