name: PyInstaller

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'salmon_run_notifier.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'salmon_run_notifier.exe'